# Generated by Django 3.1.2 on 2020-11-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
